# Generated by Django 4.2 on 2023-04-26 16:59

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product_offer_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
