# Generated by Django 4.2.4 on 2023-08-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_url',
            field=models.URLField(blank=True),
        ),
    ]
