# Generated by Django 4.2.4 on 2023-08-18 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image_url',
            new_name='product_image',
        ),
    ]
